### ISSUE TITLE
After quiting and saving regulary, the game cant be startet uncapped anymore

### ISSUE THREAD

**Issue by Penk0** [uberhalit/EldenRingFpsUnlockAndMore#34] opened 2022-02-27 11:31 UTC
If you save and quit the game via ingame menue and you try to restart the game with your mod its just not working anymore.

**Comment by uberhalit** [comment] 2022-02-27 13:31
Are you using the latest 0.0.0.4? I'll need some more info on this.

**Comment by Fantazstic** [comment] 2022-02-27 18:49
> Are you using the latest 0.0.0.4? I'll need some more info on this.

I also noticed this. The workaround I'm using is to just close the mod, then open the mod again to get the first patch to always work.

To reproduce:

1. Open Mod
2. Start Elden Ring from the Mod
3. First patch worked, FPS is unlocked
4. Quit Elden Ring but __keep Mod open from previously__
5. Open Elden Ring again (from the Mod or just game shortcut)
6. Try to patch, which doesn't work

To fix after reproducing:

1. Close Mod and Elden Ring
2. Open Mod
3. Start Elden Ring from the Mod

I am thinking the mod needs to be able to search again/re-search for the game .exe because the first instance of the game was closed and patching the second or further instances only tries to patch the wrong instance?

**Comment by Penk0** [comment] 2022-02-27 19:20
So you want me to alt f4 Elden ring from now on? Is it saving the game automatically? 
I’ll try to get it working with your tip again


Von meinem iPhone gesendet

**Comment by agentoranger** [comment] 2022-02-27 22:01
I typically Save and Alt+F4 as it took me too long to get the Exit Game option in the menu, I didn't know the menu option existed until my 3rd launch of the game as it did like to complain about the unclean exit.  Not a big deal for me, but an interesting problem, I might try to reproduce this later.  Perhaps the app is doing something special to optimize the experience upon a graceful relaunch of the game, though I cant say I know enough about that for my guess to be worth anything.

**Comment by Penk0** [comment] 2022-02-27 22:11
How to you save? 

Von meinem iPhone gesendet

**Comment by uberhalit** [comment] 2022-02-28 02:15
Fixed with 0.0.0.5

**Closed by uberhalit** 2022-02-28 02:15 UTC
Labels: bug
